import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Joao',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Dayane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Carvão 3Kg',
      slug: 'carvao-3kg',
      category: 'Churrasco',
      image: '/images/carvao.jpg',
      price: 9.99,
      brand: 'Bom de Brasa',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Carvão de excelente qualidade',
    },
    {
      name: 'Arroz 5Kg',
      slug: 'arroz-5kg',
      category: 'Grãos',
      image: '/images/arroz.jpg',
      price: 18.85,
      brand: 'Prato Fino',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Arroz de alta qualidade',
    },
    {
      name: 'Leite 1L',
      slug: 'leite-1L',
      category: 'Leite',
      image: '/images/leite.jpg',
      price: 3.35,
      brand: 'Piracanjuba',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Leite de alta qualidade',
    },
    {
      name: 'Feijão Preto 1Kg',
      slug: 'fejao-preto',
      category: 'Grãos',
      image: '/images/feijao.jpg',
      price: 6.59,
      brand: 'Urbano',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Feijão preto selecionado',
    },
    {
      name: 'Amaciante 2L',
      slug: 'limpeza-amaciante',
      category: 'Limpeza',
      image: '/images/amaciante.jpg',
      price: 4.95,
      brand: 'Ypê',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Amaciante de alta qualidade',
    },
    {
      name: 'Macarrão 500gr',
      slug: 'massas-macarrao',
      category: 'Massas',
      image: '/images/macarrao.jpg',
      price: 2.89,
      brand: 'Galo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Macarrão de excelente qualidade',
    },
  ],
};
export default data;
